module.exports = {
  apps: [
    {
      name: "db-schema",
      script: "bash",
      args: "-c 'npm install && tsc -b && npm run seed:db && npm run refresh:views'",
      cwd: "./db",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "api",
      script: "bash",
      args: "-c 'tsc -b && npm run start'",
      cwd: "./api",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "ws",
      script: "bash",
      args: "-c 'tsc -b && npm run start'",
      cwd: "./ws",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "engine",
      script: "bash",
      args: "-c 'tsc -b && npm run start'",
      cwd: "./engine",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "mm",
      script: "bash",
      args: "-c 'tsc -b && npm run start'",
      cwd: "./mm",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "db-service",
      script: "bash",
      args: "-c 'tsc -b && npm run start'",
      cwd: "./db",
      autorestart: false,
      wait_ready: false,
    },
    {
      name: "frontend",
      script: "bash",
      args: "-c 'npm install && npm run dev'",
      cwd: "./frontend",
    },
  ],
};
